### ISSUE TITLE
The auto-build is broken.

### ISSUE THREAD

**Issue by shawphy** [gamemanual0/gm0-translations#1]
The last version was Aug 12, 2024.

**Comment by abidingabi** [comment]
Closed by https://github.com/gamemanual0/gm0-translations/commit/4ee2eb81335ff90f790a93450f224721cfe16b36, which was inspired by https://github.com/wpilibsuite/frc-docs-translations/commit/cb081b3246919cb3598ca4eb03d304d65b4afd24.

**Comment by shawphy** [comment]
Thank you!
However, it looks like there's still a problem on readthedocs.org. 

https://app.readthedocs.org/projects/gm0-zh-cn/builds/
https://app.readthedocs.org/projects/gm0-es/builds/
https://app.readthedocs.org/projects/gm0-ro/builds/

**Comment by abidingabi** [comment]
Oops, sorry for not noticing that before closing the issue the first time. This has been fixed with https://github.com/gamemanual0/gm0-translations/commit/e2c62c0aa9b8ff06d1d59ef848ed4f291fe592ab.
![image](https://github.com/user-attachments/assets/408bc53a-0c17-44e6-a3e1-c4c76ec9f4ac)
